apiVersion: apps/v1
kind: Deployment
metadata:
  name: jakartaee-microprofile
  labels:
    app: jakartaee-microprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jakartaee-microprofile
  template:
    metadata:
      labels:
        app: jakartaee-microprofile
    spec:
      containers:
      - name: jakartaee-microprofile
        image: us-east1-docker.pkg.dev/PROJECT_ID/ml-java-workshopp/ml-java-workshopp-app
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 9080
        env:
        - name: HUGGING_FACE_API_KEY
          valueFrom:
            secretKeyRef:
              name: huggingfacekey
              key: HUGGING_FACE_API_KEY
        
