apiVersion: apps/v1
kind: Deployment
metadata:
  name: jakartaee-microprofile
  labels:
    app: jakartaee-microprofile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jakartaee-microprofile
  template:
    metadata:
      labels:
        app: jakartaee-microprofile
    spec:
      containers:
      - name: jakartaee-microprofile
        image: us-east1-docker.pkg.dev/PROJECT_ID/ml-java-workshopp/ml-java-workshopp-app
        ports:
        - containerPort: 9080
        env:
        - name: HUGGING_FACE_API_KEY
          value: "INSERT_API_KEY
